export type Empresa = {
  id: string;
  codigo: number;
  nome_fantasia: string;
  razao_social: string;
  cnpj: string;
  inscricao_estadual: string;
  endereco: string;
  endereco_numero: string;
  bairro: string;
  cidade: string;
  estado: string;
  cep: string;
  contato: string;
  email: string;
  regime: string;
  tipoEmpresaId: string;
  empresa_parent_id: string | null;
  status: string;
  numero_usuario: string;
  createdAt: string;
  updatedAt: string;
};
