export type MotoristaBase = {
  nome: string;
  cpf: string;
  rg: string;
  dataNascimento: string;
  contato: string;
  email: string;
  cep: string;
  numero: string;
  rua: string;
  complemento?: string;
  bairro: string;
  cidade: string;
  estado: string;
  observacao: string;
  numeroCnh: string;
  categoria: string;
  emissaocnh: string;
  validadecnh: string;
};
