export const estados = [
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "AC", nome: "Acre" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "RR", nome: "Roraima" },
];
